// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/1/17 17:16:13
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/myProjects/视频/LibreTV/libretv-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/myProjects/视频/LibreTV/libretv-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/myProjects/视频/LibreTV/libretv-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/myProjects/视频/LibreTV/libretv-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/myProjects/视频/LibreTV/libretv-nuxt/plugins/**/*.{js,ts,mjs}","D:/myProjects/视频/LibreTV/libretv-nuxt/composables/**/*.{js,ts,mjs}","D:/myProjects/视频/LibreTV/libretv-nuxt/utils/**/*.{js,ts,mjs}","D:/myProjects/视频/LibreTV/libretv-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/myProjects/视频/LibreTV/libretv-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/myProjects/视频/LibreTV/libretv-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/myProjects/视频/LibreTV/libretv-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;